# Generated by Django 5.0.6 on 2024-05-30 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIC', models.CharField(max_length=100)),
                ('PC_name', models.CharField(max_length=100)),
                ('pc_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('tablet', 'Tablet')], default='desktop', max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('network', 'Network')], default='software', max_length=10)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
