# Generated by Django 5.0.6 on 2024-05-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_it_request_pc_type_it_request_eq_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='it_request',
            old_name='PC_name',
            new_name='eq_name',
        ),
    ]
