# Generated by Django 5.0.6 on 2024-05-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='Requestor',
        ),
    ]
