# Generated by Django 5.0.6 on 2024-05-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_user_request_requestor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Requestor',
            new_name='user',
        ),
    ]
