# Generated by Django 5.0.6 on 2024-05-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_request_it_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_request',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='requested', max_length=10),
        ),
    ]
