# Generated by Django 5.0.6 on 2024-05-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_it_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it_request',
            name='PIC',
        ),
    ]
