# Generated by Django 5.0.6 on 2024-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_it_request_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='issue',
            field=models.CharField(choices=[('Software', 'software'), ('Hardware', 'hardware'), ('Network', 'network')], default='Software', max_length=10),
        ),
        migrations.AlterField(
            model_name='it_request',
            name='pc_type',
            field=models.CharField(choices=[('Desktop', 'desktop'), ('Laptop', 'laptop'), ('Tablet', 'tablet')], default='Desktop', max_length=10),
        ),
        migrations.AlterField(
            model_name='it_request',
            name='status',
            field=models.CharField(choices=[('Requested', 'requested'), ('Completed', 'completed'), ('Delayed', 'delayed')], default='Requested', max_length=10),
        ),
    ]
