# Generated by Django 5.0.6 on 2024-06-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_pc_name_it_request_eq_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='eq_type',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Others', 'Others')], default='Desktop', max_length=100),
        ),
        migrations.AlterField(
            model_name='it_request',
            name='issue',
            field=models.CharField(choices=[('Account Creation/Deletion', 'Account creation/deletion'), ('Password Reset/Unlock', 'Password reset/unlock'), ('Server Access', 'Server access'), ('Application InstallationTroubleshoot', 'Application installationtroubleshoot'), ('Security Incident Report', 'Security incident report'), ('Data Backup/Recovery', 'Data backup/recovery'), ('Hardware Installation', 'Hardware installation'), ('Network', 'Network')], default='Software', max_length=100),
        ),
        migrations.AlterField(
            model_name='it_request',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Requested', max_length=100),
        ),
    ]
