# Generated by Django 5.0.6 on 2024-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_it_request_eq_type_alter_it_request_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='eq_type',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Network Devices', 'Network devices'), ('Peripherals', 'Peripherals')], default='Desktop', max_length=100),
        ),
        migrations.AlterField(
            model_name='it_request',
            name='issue',
            field=models.CharField(choices=[('Account Creation/Deletion', 'Account creation/deletion'), ('Password Reset/Unlock', 'Password reset/unlock'), ('Server Access', 'Server access'), ('Application Installation', 'Application installation'), ('Troubleshoot', 'Troubleshoot'), ('Security Incident Report', 'Security incident report'), ('Data Backup/Recovery', 'Data backup/recovery'), ('Hardware Installation', 'Hardware installation'), ('Network', 'Network')], max_length=100),
        ),
    ]
